#!/bin/sh
CURRENT_DIR=$(cd $(dirname "$0"); pwd)

while getopts "ruhd:" opts; do
  case $opts in
    f)
      force=1
      ;;
    r)
      remove=1
      ;;
    d)
      path=$OPTARG
      ;;
    h)
      echo "Usage: $0 [-frh] [-d path]"
      echo "    -f force to update existing dot files."
      echo "    -r remove all dot files installed."
      echo "    -d directory to place dot files."
      exit 0
      ;;
  esac
done

# Assuming the directory we place the current directory
# must be the home directory. If not, use -d option.
if [ "x$path" = "x" ]; then
  path=$(dirname "$CURRENT_DIR")
fi

for i in "${CURRENT_DIR}"/.*
do
  if [ ! -e "${i}" ]; then
    continue
  fi

  f=`basename "${i}"`
  ignored=0
  for ignore in . .. .svn .git .gitignore .gitmodules .DS_Store
  do
    if [ "${f}" = "${ignore}" ]; then
      ignored=1
      continue
    fi
  done
  if [ "${ignored}" = "1" ]; then
    continue
  fi

  if [ -e "${path}/${f}" -o -h "${path}/${f}" ]; then
    echo "${f} already exists."
    if [ "$force" -o "$remove" ]; then
      echo "remove ${f}."
      rm -rf "${path}/${f}"
    else
      continue
    fi
  fi
  if [ ! "$remove" ]; then
    echo "create symlink ${f} to ${path}."
    ln -s "${i}" "${path}/${f}"
  fi
done
